before:
  hooks:
    # - make docker-push
    - go generate ./...

builds:
  - env:
    - CGO_ENABLED=0
  - main: ./
    id: "aesir"
    binary: dist/bin/aesir
    # skip: true
    goos:
      - linux
      - darwin
      - windows

  # - main: ./cmd/aesir-api
  #   id: "aesir-api"
  #   binary: aesir-api
  #   goos:
  #     - linux
  #     - darwin
  #     - windows

  # - main: ./cmd/aesir-docs-desktop
  #   id: "aesir-docs-desktop"
  #   binary: aesir-docs-desktop
  #   goos:
  #     - linux
  #     - darwin
  #     - windows

upx:
  - enabled: true
  - compress: best

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

env_files:
  gitlab_token: ~/nope
  gitea_token: ~/nope