package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.40

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"strings"
	"time"

	"github.com/nexentra/aesir/ent"
	"github.com/nexentra/aesir/evaluator"
	"github.com/nexentra/aesir/graph/generated"
	"github.com/nexentra/aesir/graph/model"
	"github.com/nexentra/aesir/lexer"
	"github.com/nexentra/aesir/object"
	"github.com/nexentra/aesir/parser"
)

// EvaluateSnippet is the resolver for the EvaluateSnippet field.
func (r *mutationResolver) EvaluateSnippet(ctx context.Context, input model.EvalInput) (*ent.Eval, error) {
	old := os.Stdout // keep backup of the real stdout
	f, w, _ := os.Pipe()
	os.Stdout = w
	env := object.NewEnvironment()
	l := lexer.New(input.Snippet)
	p := parser.New(l)
	program := p.ParseProgram()
	if len(p.Errors()) != 0 {
		return &ent.Eval{}, fmt.Errorf("error parsing input: %v", p.Errors())
	}
	evaluated := evaluator.Eval(program, env)
	fmt.Println(evaluated.Inspect())
	outC := make(chan string)
	// copy the output in a separate goroutine so printing can't block indefinitely
	go func() {
		var buf bytes.Buffer
		io.Copy(&buf, f)
		outC <- buf.String()
	}()

	// back to normal state
	w.Close()
	os.Stdout = old // restoring the real stdout
	out := <-outC

	return r.Client.Eval.Create().
		SetSnippet(out).
		SetResult(strings.Split(out, "\n")).
		SetTime(time.Now().Local().String()).
		Save(ctx)
}

// Mock is the resolver for the Mock field.
func (r *queryResolver) Mock(ctx context.Context, input string) (string, error) {
	return "", fmt.Errorf("not implemented: Mock - Mock")
}

// GetEvaluatedSnippets is the resolver for the GetEvaluatedSnippets field.
func (r *subscriptionResolver) GetEvaluatedSnippets(ctx context.Context) (<-chan []*ent.Eval, error) {
	ch := make(chan []*ent.Eval)

	go func() {
		defer close(ch)

		for {
			time.Sleep(1 * time.Second)

			t, err := r.Client.Eval.Query().All(ctx)
			if err != nil {
				fmt.Println("Error getting evaluated snippets. ERROR: ", err)
				// close(ch)
				// return
			}

			select {
			case <-ctx.Done():
				fmt.Println("Subscription closed.")
				return

			case ch <- t:
				// Our message went through, do nothing
			}

		}
	}()
	return ch, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Subscription returns generated.SubscriptionResolver implementation.
func (r *Resolver) Subscription() generated.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }