// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Eval struct {
	Snippet string `json:"snippet"`
	Result  string `json:"result"`
}

type EvalInput struct {
	Snippet string `json:"snippet"`
}

type NewTodo struct {
	Text     string `json:"text"`
	UserName string `json:"userName"`
}
