// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"

	"entgo.io/contrib/entgql"
	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/99designs/gqlgen/graphql"
	"github.com/99designs/gqlgen/graphql/errcode"
	"github.com/nexentra/aesir/ent/eval"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// Common entgql types.
type (
	Cursor         = entgql.Cursor[int]
	PageInfo       = entgql.PageInfo[int]
	OrderDirection = entgql.OrderDirection
)

func orderFunc(o OrderDirection, field string) func(*sql.Selector) {
	if o == entgql.OrderDirectionDesc {
		return Desc(field)
	}
	return Asc(field)
}

const errInvalidPagination = "INVALID_PAGINATION"

func validateFirstLast(first, last *int) (err *gqlerror.Error) {
	switch {
	case first != nil && last != nil:
		err = &gqlerror.Error{
			Message: "Passing both `first` and `last` to paginate a connection is not supported.",
		}
	case first != nil && *first < 0:
		err = &gqlerror.Error{
			Message: "`first` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	case last != nil && *last < 0:
		err = &gqlerror.Error{
			Message: "`last` on a connection cannot be less than zero.",
		}
		errcode.Set(err, errInvalidPagination)
	}
	return err
}

func collectedField(ctx context.Context, path ...string) *graphql.CollectedField {
	fc := graphql.GetFieldContext(ctx)
	if fc == nil {
		return nil
	}
	field := fc.Field
	oc := graphql.GetOperationContext(ctx)
walk:
	for _, name := range path {
		for _, f := range graphql.CollectFields(oc, field.Selections, nil) {
			if f.Alias == name {
				field = f
				continue walk
			}
		}
		return nil
	}
	return &field
}

func hasCollectedField(ctx context.Context, path ...string) bool {
	if graphql.GetFieldContext(ctx) == nil {
		return true
	}
	return collectedField(ctx, path...) != nil
}

const (
	edgesField      = "edges"
	nodeField       = "node"
	pageInfoField   = "pageInfo"
	totalCountField = "totalCount"
)

func paginateLimit(first, last *int) int {
	var limit int
	if first != nil {
		limit = *first + 1
	} else if last != nil {
		limit = *last + 1
	}
	return limit
}

// EvalEdge is the edge representation of Eval.
type EvalEdge struct {
	Node   *Eval  `json:"node"`
	Cursor Cursor `json:"cursor"`
}

// EvalConnection is the connection containing edges to Eval.
type EvalConnection struct {
	Edges      []*EvalEdge `json:"edges"`
	PageInfo   PageInfo    `json:"pageInfo"`
	TotalCount int         `json:"totalCount"`
}

func (c *EvalConnection) build(nodes []*Eval, pager *evalPager, after *Cursor, first *int, before *Cursor, last *int) {
	c.PageInfo.HasNextPage = before != nil
	c.PageInfo.HasPreviousPage = after != nil
	if first != nil && *first+1 == len(nodes) {
		c.PageInfo.HasNextPage = true
		nodes = nodes[:len(nodes)-1]
	} else if last != nil && *last+1 == len(nodes) {
		c.PageInfo.HasPreviousPage = true
		nodes = nodes[:len(nodes)-1]
	}
	var nodeAt func(int) *Eval
	if last != nil {
		n := len(nodes) - 1
		nodeAt = func(i int) *Eval {
			return nodes[n-i]
		}
	} else {
		nodeAt = func(i int) *Eval {
			return nodes[i]
		}
	}
	c.Edges = make([]*EvalEdge, len(nodes))
	for i := range nodes {
		node := nodeAt(i)
		c.Edges[i] = &EvalEdge{
			Node:   node,
			Cursor: pager.toCursor(node),
		}
	}
	if l := len(c.Edges); l > 0 {
		c.PageInfo.StartCursor = &c.Edges[0].Cursor
		c.PageInfo.EndCursor = &c.Edges[l-1].Cursor
	}
	if c.TotalCount == 0 {
		c.TotalCount = len(nodes)
	}
}

// EvalPaginateOption enables pagination customization.
type EvalPaginateOption func(*evalPager) error

// WithEvalOrder configures pagination ordering.
func WithEvalOrder(order *EvalOrder) EvalPaginateOption {
	if order == nil {
		order = DefaultEvalOrder
	}
	o := *order
	return func(pager *evalPager) error {
		if err := o.Direction.Validate(); err != nil {
			return err
		}
		if o.Field == nil {
			o.Field = DefaultEvalOrder.Field
		}
		pager.order = &o
		return nil
	}
}

// WithEvalFilter configures pagination filter.
func WithEvalFilter(filter func(*EvalQuery) (*EvalQuery, error)) EvalPaginateOption {
	return func(pager *evalPager) error {
		if filter == nil {
			return errors.New("EvalQuery filter cannot be nil")
		}
		pager.filter = filter
		return nil
	}
}

type evalPager struct {
	reverse bool
	order   *EvalOrder
	filter  func(*EvalQuery) (*EvalQuery, error)
}

func newEvalPager(opts []EvalPaginateOption, reverse bool) (*evalPager, error) {
	pager := &evalPager{reverse: reverse}
	for _, opt := range opts {
		if err := opt(pager); err != nil {
			return nil, err
		}
	}
	if pager.order == nil {
		pager.order = DefaultEvalOrder
	}
	return pager, nil
}

func (p *evalPager) applyFilter(query *EvalQuery) (*EvalQuery, error) {
	if p.filter != nil {
		return p.filter(query)
	}
	return query, nil
}

func (p *evalPager) toCursor(e *Eval) Cursor {
	return p.order.Field.toCursor(e)
}

func (p *evalPager) applyCursors(query *EvalQuery, after, before *Cursor) (*EvalQuery, error) {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	for _, predicate := range entgql.CursorsPredicate(after, before, DefaultEvalOrder.Field.column, p.order.Field.column, direction) {
		query = query.Where(predicate)
	}
	return query, nil
}

func (p *evalPager) applyOrder(query *EvalQuery) *EvalQuery {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	query = query.Order(p.order.Field.toTerm(direction.OrderTermOption()))
	if p.order.Field != DefaultEvalOrder.Field {
		query = query.Order(DefaultEvalOrder.Field.toTerm(direction.OrderTermOption()))
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return query
}

func (p *evalPager) orderExpr(query *EvalQuery) sql.Querier {
	direction := p.order.Direction
	if p.reverse {
		direction = direction.Reverse()
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(p.order.Field.column)
	}
	return sql.ExprFunc(func(b *sql.Builder) {
		b.Ident(p.order.Field.column).Pad().WriteString(string(direction))
		if p.order.Field != DefaultEvalOrder.Field {
			b.Comma().Ident(DefaultEvalOrder.Field.column).Pad().WriteString(string(direction))
		}
	})
}

// Paginate executes the query and returns a relay based cursor connection to Eval.
func (e *EvalQuery) Paginate(
	ctx context.Context, after *Cursor, first *int,
	before *Cursor, last *int, opts ...EvalPaginateOption,
) (*EvalConnection, error) {
	if err := validateFirstLast(first, last); err != nil {
		return nil, err
	}
	pager, err := newEvalPager(opts, last != nil)
	if err != nil {
		return nil, err
	}
	if e, err = pager.applyFilter(e); err != nil {
		return nil, err
	}
	conn := &EvalConnection{Edges: []*EvalEdge{}}
	ignoredEdges := !hasCollectedField(ctx, edgesField)
	if hasCollectedField(ctx, totalCountField) || hasCollectedField(ctx, pageInfoField) {
		hasPagination := after != nil || first != nil || before != nil || last != nil
		if hasPagination || ignoredEdges {
			if conn.TotalCount, err = e.Clone().Count(ctx); err != nil {
				return nil, err
			}
			conn.PageInfo.HasNextPage = first != nil && conn.TotalCount > 0
			conn.PageInfo.HasPreviousPage = last != nil && conn.TotalCount > 0
		}
	}
	if ignoredEdges || (first != nil && *first == 0) || (last != nil && *last == 0) {
		return conn, nil
	}
	if e, err = pager.applyCursors(e, after, before); err != nil {
		return nil, err
	}
	if limit := paginateLimit(first, last); limit != 0 {
		e.Limit(limit)
	}
	if field := collectedField(ctx, edgesField, nodeField); field != nil {
		if err := e.collectField(ctx, graphql.GetOperationContext(ctx), *field, []string{edgesField, nodeField}); err != nil {
			return nil, err
		}
	}
	e = pager.applyOrder(e)
	nodes, err := e.All(ctx)
	if err != nil {
		return nil, err
	}
	conn.build(nodes, pager, after, first, before, last)
	return conn, nil
}

// EvalOrderField defines the ordering field of Eval.
type EvalOrderField struct {
	// Value extracts the ordering value from the given Eval.
	Value    func(*Eval) (ent.Value, error)
	column   string // field or computed.
	toTerm   func(...sql.OrderTermOption) eval.OrderOption
	toCursor func(*Eval) Cursor
}

// EvalOrder defines the ordering of Eval.
type EvalOrder struct {
	Direction OrderDirection  `json:"direction"`
	Field     *EvalOrderField `json:"field"`
}

// DefaultEvalOrder is the default ordering of Eval.
var DefaultEvalOrder = &EvalOrder{
	Direction: entgql.OrderDirectionAsc,
	Field: &EvalOrderField{
		Value: func(e *Eval) (ent.Value, error) {
			return e.ID, nil
		},
		column: eval.FieldID,
		toTerm: eval.ByID,
		toCursor: func(e *Eval) Cursor {
			return Cursor{ID: e.ID}
		},
	},
}

// ToEdge converts Eval into EvalEdge.
func (e *Eval) ToEdge(order *EvalOrder) *EvalEdge {
	if order == nil {
		order = DefaultEvalOrder
	}
	return &EvalEdge{
		Node:   e,
		Cursor: order.Field.toCursor(e),
	}
}
