// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/nexentra/aesir/ent/eval"
	"github.com/nexentra/aesir/ent/predicate"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeEval = "Eval"
)

// EvalMutation represents an operation that mutates the Eval nodes in the graph.
type EvalMutation struct {
	config
	op            Op
	typ           string
	id            *int
	snippet       *string
	result        *[]string
	appendresult  []string
	time          *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Eval, error)
	predicates    []predicate.Eval
}

var _ ent.Mutation = (*EvalMutation)(nil)

// evalOption allows management of the mutation configuration using functional options.
type evalOption func(*EvalMutation)

// newEvalMutation creates new mutation for the Eval entity.
func newEvalMutation(c config, op Op, opts ...evalOption) *EvalMutation {
	m := &EvalMutation{
		config:        c,
		op:            op,
		typ:           TypeEval,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEvalID sets the ID field of the mutation.
func withEvalID(id int) evalOption {
	return func(m *EvalMutation) {
		var (
			err   error
			once  sync.Once
			value *Eval
		)
		m.oldValue = func(ctx context.Context) (*Eval, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Eval.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEval sets the old Eval of the mutation.
func withEval(node *Eval) evalOption {
	return func(m *EvalMutation) {
		m.oldValue = func(context.Context) (*Eval, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EvalMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EvalMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EvalMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *EvalMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Eval.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetSnippet sets the "snippet" field.
func (m *EvalMutation) SetSnippet(s string) {
	m.snippet = &s
}

// Snippet returns the value of the "snippet" field in the mutation.
func (m *EvalMutation) Snippet() (r string, exists bool) {
	v := m.snippet
	if v == nil {
		return
	}
	return *v, true
}

// OldSnippet returns the old "snippet" field's value of the Eval entity.
// If the Eval object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EvalMutation) OldSnippet(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldSnippet is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldSnippet requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldSnippet: %w", err)
	}
	return oldValue.Snippet, nil
}

// ResetSnippet resets all changes to the "snippet" field.
func (m *EvalMutation) ResetSnippet() {
	m.snippet = nil
}

// SetResult sets the "result" field.
func (m *EvalMutation) SetResult(s []string) {
	m.result = &s
	m.appendresult = nil
}

// Result returns the value of the "result" field in the mutation.
func (m *EvalMutation) Result() (r []string, exists bool) {
	v := m.result
	if v == nil {
		return
	}
	return *v, true
}

// OldResult returns the old "result" field's value of the Eval entity.
// If the Eval object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EvalMutation) OldResult(ctx context.Context) (v []string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldResult is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldResult requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldResult: %w", err)
	}
	return oldValue.Result, nil
}

// AppendResult adds s to the "result" field.
func (m *EvalMutation) AppendResult(s []string) {
	m.appendresult = append(m.appendresult, s...)
}

// AppendedResult returns the list of values that were appended to the "result" field in this mutation.
func (m *EvalMutation) AppendedResult() ([]string, bool) {
	if len(m.appendresult) == 0 {
		return nil, false
	}
	return m.appendresult, true
}

// ResetResult resets all changes to the "result" field.
func (m *EvalMutation) ResetResult() {
	m.result = nil
	m.appendresult = nil
}

// SetTime sets the "time" field.
func (m *EvalMutation) SetTime(s string) {
	m.time = &s
}

// Time returns the value of the "time" field in the mutation.
func (m *EvalMutation) Time() (r string, exists bool) {
	v := m.time
	if v == nil {
		return
	}
	return *v, true
}

// OldTime returns the old "time" field's value of the Eval entity.
// If the Eval object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EvalMutation) OldTime(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTime is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTime requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTime: %w", err)
	}
	return oldValue.Time, nil
}

// ResetTime resets all changes to the "time" field.
func (m *EvalMutation) ResetTime() {
	m.time = nil
}

// Where appends a list predicates to the EvalMutation builder.
func (m *EvalMutation) Where(ps ...predicate.Eval) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the EvalMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *EvalMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Eval, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *EvalMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *EvalMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Eval).
func (m *EvalMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EvalMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.snippet != nil {
		fields = append(fields, eval.FieldSnippet)
	}
	if m.result != nil {
		fields = append(fields, eval.FieldResult)
	}
	if m.time != nil {
		fields = append(fields, eval.FieldTime)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EvalMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case eval.FieldSnippet:
		return m.Snippet()
	case eval.FieldResult:
		return m.Result()
	case eval.FieldTime:
		return m.Time()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EvalMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case eval.FieldSnippet:
		return m.OldSnippet(ctx)
	case eval.FieldResult:
		return m.OldResult(ctx)
	case eval.FieldTime:
		return m.OldTime(ctx)
	}
	return nil, fmt.Errorf("unknown Eval field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EvalMutation) SetField(name string, value ent.Value) error {
	switch name {
	case eval.FieldSnippet:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetSnippet(v)
		return nil
	case eval.FieldResult:
		v, ok := value.([]string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetResult(v)
		return nil
	case eval.FieldTime:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTime(v)
		return nil
	}
	return fmt.Errorf("unknown Eval field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EvalMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EvalMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EvalMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown Eval numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EvalMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EvalMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EvalMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Eval nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EvalMutation) ResetField(name string) error {
	switch name {
	case eval.FieldSnippet:
		m.ResetSnippet()
		return nil
	case eval.FieldResult:
		m.ResetResult()
		return nil
	case eval.FieldTime:
		m.ResetTime()
		return nil
	}
	return fmt.Errorf("unknown Eval field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EvalMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EvalMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EvalMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EvalMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EvalMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EvalMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EvalMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Eval unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EvalMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Eval edge %s", name)
}
