import { Toaster } from '@/shadcn/components/ui/toaster'
import '../globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ThemeProvider } from '@/components/ui/theme-provider'
import CustomCursor from '@/components/ui/cursor'
import AnimatedBackground from '@/components/ui/animated-background'
import NextTopLoader from 'nextjs-toploader';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter?.className}>
      <NextTopLoader />
      <AnimatedBackground/>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
        >
          <CustomCursor />
          {children}
        </ThemeProvider>
      </body>
      <Toaster />
    </html>
  )
}
