name: Aesir CI

on: 
  push:
  pull_request:
    branches: [main]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: git fetch --force --tags

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Verify dependencies
        run: go mod verify
    
      - name: Build
        run: go build -v ./...
    
      - name: Run go vet
        run: go vet ./...
    
      - name: Install staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest
    
      - name: Run staticcheck
        run: staticcheck ./...
    
      - name: Install golint
        run: go install golang.org/x/lint/golint@latest
    
      - name: Run golint
        run: golint ./...
    
      - name: Run tests
        run: go test -race -vet=off ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GO_RELEASER_GITHUB_TOKEN }}